name: My first GitHub Action
on: [push]
jobs:
    build-app:
        runs-on: ubuntu-latest
        steps: 
           - uses: actions/checkout@v2
           - uses: actions/setup-node@v2
             with:
                 node-version: '14'
           - name: Build the project
             run:  yarn build
           - name: Install noe_modules
             run: yarn     
           - name: Setup finished
             run: echo "HURRAY!!!" 
           